config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  get 'cars/new'
  get 'cars/create'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cars#index"

  #definitions des routes une par une, sans refacto pour la pratique en utilisant resources
  get "cars/", to: "cars#index", as: "cars"
  get "cars/new", to: "cars#new", as: "new_car"
  get "cars/:id", to: "cars#show", as: "car"
  post "cars", to: "cars#create"
  get "cars/:id/edit", to: "cars#edit", as: "edit_car"
  patch "cars/:id", to: "cars#update"
  delete "cars/:id", to: "cars#destroy"

  get "cars/:car_id/maintenance_items/", to: "maintenance_items#index", as: "car_maintenance_items"
  get "cars/:car_id/maintenance_items/call_maintenance", to: "maintenance_items#call_maintenance", as: "car_maintenance_items_call_maintenance"
  get "cars/:car_id/maintenance_items/new", to: "maintenance_items#new", as: "new_car_maintenance_item"
  get "cars/:car_id/maintenance_items/:id", to: "maintenance_items#show", as: "car_maintenance_item"
  post "cars/:car_id/maintenance_items", to: "maintenance_items#create"
  get "cars/:car_id/maintenance_items/:id/edit", to: "maintenance_items#edit", as: "edit_car_maintenance_item"
  patch "cars/:car_id/maintenance_items/:id", to: "maintenance_items#update"
  delete "cars/:car_id/maintenance_items/:id", to: "maintenance_items#destroy"

  get "cars/:car_id/garage_stops/", to: "garage_stops#index", as: "car_garage_stops"
  get "cars/:car_id/garage_stops/new", to: "garage_stops#new", as: "new_car_garage_stop"
  get "cars/:car_id/garage_stops/picture_analysis", to: "garage_stops#picture_analysis", as: "new_car_garage_stop_picture_analysis"
  post "cars/:car_id/garage_stops/invoice_review", to: "garage_stops#invoice_review", as: "new_car_garage_stop_invoice_review"
  get "cars/:car_id/garage_stops/:id", to: "garage_stops#show", as: "car_garage_stop"
  post "cars/:car_id/garage_stops", to: "garage_stops#create"
  get "cars/:car_id/garage_stops/:id/edit", to: "garage_stops#edit", as: "edit_car_garage_stop"
  patch "cars/:car_id/garage_stops/:id", to: "garage_stops#update"
  delete "cars/:car_id/garage_stops/:id", to: "garage_stops#destroy"

  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/", to: "stop_items#index", as: "car_garage_stop_stop_items"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/new", to: "stop_items#new", as: "new_car_garage_stop_stop_item"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#show", as: "car_garage_stop_stop_item"
  post "cars/:car_id/garage_stops/:garage_stop_id/stop_items", to: "stop_items#create"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id/edit", to: "stop_items#edit", as: "edit_car_garage_stop_stop_item"
  patch "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#update"
  delete "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#destroy"

  get "garages/", to: "garages#index", as: "garages"
  get "garages/new", to: "garages#new", as: "new_garage"
  get "garages/:id", to: "garages#show", as: "garage"
  post "garages", to: "garages#create"
  get "garages/:id/edit", to: "garages#edit", as: "edit_garage"
  patch "garages/:id", to: "garages#update"
  delete "garages/:id", to: "garages#destroy"

  get "picture_analysis", to: "image_data#picture_analysis", as: "new_picture_analysis"
  post "invoice_review", to: "image_data#invoice_review", as: "new_invoice_review"

end

app/models/stop_item.rb
class StopItem < ApplicationRecord
  belongs_to :maintenance_item
  belongs_to :garage_stop
end

app/controllers/stop_items_controller.rb
class StopItemsController < ApplicationController
  before_action :set_garage_stop_and_car
  # before_action :set_maintenance_item, only: [:show, :edit, :update]
  before_action :set_stop_item, only: [:show, :edit, :update]

  def index
    @stop_items = @garage_stop.stop_items
  end

  def show

  end

  def new
    @stop_item = StopItem.new
  end

  def create
    @stop_item = StopItem.new(stop_item_params)
    if @stop_item.save
      redirect_to car_garage_stop_stop_items_path(@garage_stop)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
        if @stop_item.update(stop_item_params)
      redirect_to car_garage_stop_stop_item_path(@garage_stop, @stop_item)
    else
      render :edit, status: :unprocessable_entity
    end
  end

private

  def set_garage_stop_and_car
    @garage_stop = GarageStop.find(params[:garage_stop_id])
    @car = @garage_stop.car
  end

  # def set_maintenance_item
  #   @maitenance_item = MaintenanceItem.find(params[:maintenance_item_id])
  # end

  def set_stop_item
    @stop_item = StopItem.find(params[:id])
  end

  def stop_item_params
    params.require(:stop_item).permit(:garage_stop_id, :maintenance_item_id, :price, :next_date_milestone, :next_km_milestone)
  end
end

app/helpers/stop_items_helper.rb
module StopItemsHelper
end

app/views/stop_items/_form.html.erb
<% is_readonly = local_assigns[:readonly] || false %>

<form action="<%= form_action %>" method="<%= form_method %>">
  <% if form_method.to_s.downcase != "post" %>
    <input type="hidden" name="_method" value="<%= form_method.upcase %>">
  <% end %>

  <label for="garage_stop_id">Arrét au garage</label>
  <input type="text" name="stop_item[garage_stop_id]" id="garage_stop_id" value="<%= @garage_stop.id %>" <%= 'readonly' if is_readonly %>><br>

  <label for="maintenance_item_id">Opération</label>
  <input type="text" name="stop_item[maintenance_item_id]" id="maintenance_item_id" value="<%= stop_item&.maintenance_item_id %>" <%= 'readonly' if is_readonly %>><br>

  <label for="price">price</label>
  <input type="number" name="stop_item[price]" id="price" value="<%=stop_item&.price %>" <%= 'readonly' if is_readonly %>><br>

  <label for="next_date_milestone">Kilométrage</label>
  <input type="date" name="stop_item[next_date_milestone]" id="next_date_milestone" value="<%=stop_item&.next_date_milestone %>" <%= 'readonly' if is_readonly %>><br>

  <label for="next_km_milestone">Cout</label>
  <input type="number" name="stop_item[next_km_milestone]" id="next_km_milestone" value="<%=stop_item&.next_km_milestone %>" <%= 'readonly' if is_readonly %>>
  <span> km</span><br>

  <% unless is_readonly %>
    <input type="submit" value="Valider">
  <% end %>
</form>

app/views/stop_items/edit.html.erb
stop_item edit

<%= render partial: 'form', locals: {
  garage_stop: @garage_stop,
  stop_item: @stop_item
  form_action: car_garage_stop_stop_item_path(@car, @garage_stop, @stop_item),
  form_method: "patch"
} %>

app/views/stop_items/index.html.erb
stop_item index

<p><%=link_to "nouveau" , new_car_garage_stop_stop_item_path(@car, @garage_stop)%></p>

<ul>
 <%@stop_items.each do |stop_item|%>
  <li><%=link_to stop_item.maintenance_item.item_name , car_garage_stop_stop_item_path(@car, @garage_stop, stop_item)%></li>
  <%end%>
</ul>

app/views/stop_items/new.html.erb
stop_item new

<%= render partial: 'form', locals: {
  garage_stop: @garage_stop,
  stop_item: @stop_item,
  form_action: car_garage_stop_stop_items_path(@car, @garage_stop),
  form_method: "post"
} %>

app/views/stop_items/show.html.erb
stop_item show

<%= render partial: 'form', locals: {
  stop_item: @stop_item,
  form_action: "#",
  form_method: "get",
  readonly: true
} %>

<a href="<%=edit_car_garage_stop_path(@car, @garage_stop)%>">Mise à jour</a>