config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  get 'cars/new'
  get 'cars/create'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cars#index"

  #definitions des routes une par une, sans refacto pour la pratique en utilisant resources
  get "cars/", to: "cars#index", as: "cars"
  get "cars/new", to: "cars#new", as: "new_car"
  get "cars/:id", to: "cars#show", as: "car"
  post "cars", to: "cars#create"
  get "cars/:id/edit", to: "cars#edit", as: "edit_car"
  patch "cars/:id", to: "cars#update"
  delete "cars/:id", to: "cars#destroy"

  get "cars/:car_id/maintenance_items/", to: "maintenance_items#index", as: "car_maintenance_items"
  get "cars/:car_id/maintenance_items/call_maintenance", to: "maintenance_items#call_maintenance", as: "car_maintenance_items_call_maintenance"
  get "cars/:car_id/maintenance_items/new", to: "maintenance_items#new", as: "new_car_maintenance_item"
  get "cars/:car_id/maintenance_items/:id", to: "maintenance_items#show", as: "car_maintenance_item"
  post "cars/:car_id/maintenance_items", to: "maintenance_items#create"
  get "cars/:car_id/maintenance_items/:id/edit", to: "maintenance_items#edit", as: "edit_car_maintenance_item"
  patch "cars/:car_id/maintenance_items/:id", to: "maintenance_items#update"
  delete "cars/:car_id/maintenance_items/:id", to: "maintenance_items#destroy"

  get "cars/:car_id/garage_stops/", to: "garage_stops#index", as: "car_garage_stops"
  get "cars/:car_id/garage_stops/new", to: "garage_stops#new", as: "new_car_garage_stop"
  get "cars/:car_id/garage_stops/picture_analysis", to: "garage_stops#picture_analysis", as: "new_car_garage_stop_picture_analysis"
  post "cars/:car_id/garage_stops/invoice_review", to: "garage_stops#invoice_review", as: "new_car_garage_stop_invoice_review"
  get "cars/:car_id/garage_stops/:id", to: "garage_stops#show", as: "car_garage_stop"
  post "cars/:car_id/garage_stops", to: "garage_stops#create"
  get "cars/:car_id/garage_stops/:id/edit", to: "garage_stops#edit", as: "edit_car_garage_stop"
  patch "cars/:car_id/garage_stops/:id", to: "garage_stops#update"
  delete "cars/:car_id/garage_stops/:id", to: "garage_stops#destroy"

  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/", to: "stop_items#index", as: "car_garage_stop_stop_items"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/new", to: "stop_items#new", as: "new_car_garage_stop_stop_item"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#show", as: "car_garage_stop_stop_item"
  post "cars/:car_id/garage_stops/:garage_stop_id/stop_items", to: "stop_items#create"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id/edit", to: "stop_items#edit", as: "edit_car_garage_stop_stop_item"
  patch "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#update"
  delete "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#destroy"

  get "garages/", to: "garages#index", as: "garages"
  get "garages/new", to: "garages#new", as: "new_garage"
  get "garages/:id", to: "garages#show", as: "garage"
  post "garages", to: "garages#create"
  get "garages/:id/edit", to: "garages#edit", as: "edit_garage"
  patch "garages/:id", to: "garages#update"
  delete "garages/:id", to: "garages#destroy"

  get "picture_analysis", to: "image_data#picture_analysis", as: "new_picture_analysis"
  post "invoice_review", to: "image_data#invoice_review", as: "new_invoice_review"

end

app/models/garage_stop.rb
class GarageStop < ApplicationRecord
  belongs_to :car
  belongs_to :garage
  has_many :stop_items

  has_many_attached :photos
end

app/controllers/garage_stops_controller.rb
class GarageStopsController < ApplicationController
  before_action :set_car
  before_action :set_garage_stop, only: [:show, :edit, :update]

  def index
    @garage_stops = @car.garage_stops
  end


  def new
    @garage_stop = GarageStop.new
  end

  def create
    @garage_stop = GarageStop.new(garage_stop_params)
    # raise

    if @garage_stop.save
      redirect_to car_garage_stops_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @garage_stop = GarageStop.find(params[:id])
  end

  def update
    if @garage_stop.update(garage_stop_params)
      redirect_to car_garage_stop_path(@car, @garage_stop)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show

  end

private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def set_garage_stop
    @garage_stop = GarageStop.find(params[:id])
  end

  def garage_stop_params
    params.require(:garage_stop).permit(:car_id, :garage_id, :date, :mileage, :cost, :comments)
  end

end

app/helpers/garage_stops_helper.rb
module GarageStopsHelper
end

app/views/garage_stops/_form.html.erb
<% is_readonly = local_assigns[:readonly] || false %>

<form action="<%= form_action %>" method="<%= form_method %>">
  <% if form_method.to_s.downcase != "post" %>
    <input type="hidden" name="_method" value="<%= form_method.upcase %>">
  <% end %>

  <label for="car_id">Voiture</label>
  <input type="text" name="garage_stop[car_id]" id="car_id" value="<%= @car.id %>" <%= 'readonly' if is_readonly %>><br>

  <label for="garage_id">Garage</label>
  <input type="text" name="garage_stop[garage_id]" id="garage_id" value="<%= garage_stop&.garage_id %>" <%= 'readonly' if is_readonly %>><br>

  <label for="date">Date</label>
  <input type="date" name="garage_stop[date]" id="date" value="<%=garage_stop&.date %>" <%= 'readonly' if is_readonly %>><br>

  <label for="mileage">Kilométrage</label>
  <input type="number" name="garage_stop[mileage]" id="mileage" value="<%=garage_stop&.mileage %>" <%= 'readonly' if is_readonly %>><br>

  <label for="cost">Cout</label>
  <input type="number" name="garage_stop[cost]" id="cost" value="<%=garage_stop&.cost %>" <%= 'readonly' if is_readonly %>>
  <span> km</span><br>

  <label for="comments">Remarques</label>
  <input type="text" name="garage_stop[comments]" id="comments" value="<%=garage_stop&.comments %>" <%= 'readonly' if is_readonly %>>
  <span> an</span><br>

  <% unless is_readonly %>
    <input type="submit" value="Valider">
  <% end %>
</form>

app/views/garage_stops/edit.html.erb
garage_stop edit

<%= render partial: 'form', locals: {
  car: @car,
  garage_stop: @garage_stop,
  form_action: car_garage_stop_path(@car, @garage_stop),
  form_method: "patch"
} %>

app/views/garage_stops/index.html.erb
garage_stop index

<p><%=link_to "nouveau" , new_car_garage_stop_path(@car)%></p>

<ul>
 <%@garage_stops.each do |stop|%>
  <li><%=link_to stop.date , car_garage_stop_path(@car, stop)%></li>
  <%end%>
</ul>

app/views/garage_stops/new.html.erb
garage_stop new

<%= render partial: 'form', locals: {
  car: @car,
  garage_stop: @garage_stop,
  form_action: car_garage_stops_path,
  form_method: "post"
} %>

app/views/garage_stops/picture_analysis.html.erb
<form action=<%=new_car_garage_stop_invoice_review_path(@car)%> method="post" enctype="multipart/form-data">charger photos
  <label for="photos">Charger photos</label>
  <input type="file" name="garage_stop[photos][]" id="photos"  multiple="multiple" >

  <div>-------------------</div>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Valider">
  <%# value="<%= garage_stop&.photos %>
</form>

<div>---------------------<br>---------------------</div>

app/views/garage_stops/show.html.erb
garage_stop show

<%= render partial: 'form', locals: {
  car: @car,
  garage_stop: @garage_stop,
  form_action: "#",
  form_method: "get",
  readonly: true
} %>

<a href="<%=edit_car_garage_stop_path(@car, @garage_stop)%>">Mise à jour</a>
<a href="<%=car_garage_stop_stop_items_path(@car, @garage_stop)%>">Opérations réalisées</a>

app/views/garage_stops/zzold_picture_analysis.html.erb
<form action=<%=new_car_garage_stop_invoice_review_path(@car)%> method="post" enctype="multipart/form-data">charger photos
  <label for="photos">Charger photos</label>
  <input type="file" name="garage_stop[photos][]" id="photos"  multiple="multiple" >

  <div>-------------------</div>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Valider">
  <%# value="<%= garage_stop&.photos %>
</form>

<div>---------------------<br>---------------------</div>