config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  get 'cars/new'
  get 'cars/create'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cars#index"

  #definitions des routes une par une, sans refacto pour la pratique en utilisant resources
  get "cars/", to: "cars#index", as: "cars"
  get "cars/new", to: "cars#new", as: "new_car"
  get "cars/:id", to: "cars#show", as: "car"
  post "cars", to: "cars#create"
  get "cars/:id/edit", to: "cars#edit", as: "edit_car"
  patch "cars/:id", to: "cars#update"
  delete "cars/:id", to: "cars#destroy"

  get "cars/:car_id/maintenance_items/", to: "maintenance_items#index", as: "car_maintenance_items"
  get "cars/:car_id/maintenance_items/call_maintenance", to: "maintenance_items#call_maintenance", as: "car_maintenance_items_call_maintenance"
  get "cars/:car_id/maintenance_items/new", to: "maintenance_items#new", as: "new_car_maintenance_item"
  get "cars/:car_id/maintenance_items/:id", to: "maintenance_items#show", as: "car_maintenance_item"
  post "cars/:car_id/maintenance_items", to: "maintenance_items#create"
  get "cars/:car_id/maintenance_items/:id/edit", to: "maintenance_items#edit", as: "edit_car_maintenance_item"
  patch "cars/:car_id/maintenance_items/:id", to: "maintenance_items#update"
  delete "cars/:car_id/maintenance_items/:id", to: "maintenance_items#destroy"

  get "cars/:car_id/garage_stops/", to: "garage_stops#index", as: "car_garage_stops"
  get "cars/:car_id/garage_stops/new", to: "garage_stops#new", as: "new_car_garage_stop"
  get "cars/:car_id/garage_stops/picture_analysis", to: "garage_stops#picture_analysis", as: "new_car_garage_stop_picture_analysis"
  post "cars/:car_id/garage_stops/invoice_review", to: "garage_stops#invoice_review", as: "new_car_garage_stop_invoice_review"
  get "cars/:car_id/garage_stops/:id", to: "garage_stops#show", as: "car_garage_stop"
  post "cars/:car_id/garage_stops", to: "garage_stops#create"
  get "cars/:car_id/garage_stops/:id/edit", to: "garage_stops#edit", as: "edit_car_garage_stop"
  patch "cars/:car_id/garage_stops/:id", to: "garage_stops#update"
  delete "cars/:car_id/garage_stops/:id", to: "garage_stops#destroy"

  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/", to: "stop_items#index", as: "car_garage_stop_stop_items"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/new", to: "stop_items#new", as: "new_car_garage_stop_stop_item"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#show", as: "car_garage_stop_stop_item"
  post "cars/:car_id/garage_stops/:garage_stop_id/stop_items", to: "stop_items#create"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id/edit", to: "stop_items#edit", as: "edit_car_garage_stop_stop_item"
  patch "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#update"
  delete "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#destroy"

  get "garages/", to: "garages#index", as: "garages"
  get "garages/new", to: "garages#new", as: "new_garage"
  get "garages/:id", to: "garages#show", as: "garage"
  post "garages", to: "garages#create"
  get "garages/:id/edit", to: "garages#edit", as: "edit_garage"
  patch "garages/:id", to: "garages#update"
  delete "garages/:id", to: "garages#destroy"

  get "picture_analysis", to: "image_data#picture_analysis", as: "new_picture_analysis"
  post "invoice_review", to: "image_data#invoice_review", as: "new_invoice_review"

end

app/models/maintenance_item.rb
class MaintenanceItem < ApplicationRecord
  belongs_to :car
  has_many :stop_items
end

app/controllers/maintenance_items_controller.rb
class MaintenanceItemsController < ApplicationController
  before_action :set_car
  before_action :set_maintenance_item, only: [:show, :edit, :update]

  def index
    # raise
    @maintenance_items = @car.maintenance_items
  end

  def show

  end

  def new
    # raise
    @maintenance_item = MaintenanceItem.new
  end

  def create
    @maintenance_item = MaintenanceItem.new(maintenance_item_params)
    @maintenance_item.car_id = @car.id
    if @maintenance_item.save
      redirect_to car_maintenance_items_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end


  def update
    if @maintenance_item.update(maintenance_item_params)
      redirect_to car_maintenance_item_path(@car, @maintenance_item)
    else
      # raise
      render :edit, status: :unprocessable_entity
    end
  end

  def call_maintenance
    create_plan()
    raise
    redirect_to maintenance_items_path(@car)
  end

private

  def set_car
    @car=Car.find(params[:car_id])
  end

  def maintenance_item_params
    params.require(:maintenance_item).permit(:car_id, :item_name, :to_do_every_x_km, :to_do_every_x_years, :one_shot_operation)
  end

  def set_maintenance_item
    @maintenance_item = MaintenanceItem.find(params[:id])
  end

    def create_prompt
    #JSON requis pour parser la réponse
    require 'json'
    #constitution du prompt
    # Liste des entretiens déjà faits ou à prévoir
    if @car.maintenance_items.any?
      maintenance_list = "Déjà listés:\n" +
        @car.maintenance_items.map do |i|
          "- #{i.item_name}, tous les #{i.to_do_every_x_km} km ou #{i.to_do_every_x_years} an(s)"
        end.join("\n") +
        "\nListe les entretiens supplémentaires (non présents ci-dessus) si applicables :"
    else
      maintenance_list = "Liste exhaustive des entretiens à prévoir :"
    end

    # Prompt
    @prompt = <<~PROMPT
      Voiture #{@car.make} #{@car.model}, #{@car.energy}, #{@car.horsepower} ch,
      1ère immat: #{@car.first_registration_date}, #{@car.mileage} km, #{@car.mileage_per_year} km/an.

      #{maintenance_list}

      Inclure si applicable : vidange huile; filtre à air; filtre carburant; filtre habitacle;
      courroie distribution; liquide frein; liquide refroidissement; pneus; embrayage; amortisseurs;
      révisions constructeur; autres opérations spécifiques modèle.

      Réponse attendue : JSON -> array de hash :
      - item_name: string ≤ 30 caractères
      - one_shot_operation: true/false
      - to_do_every_x_km: nombre ou null
      - to_do_every_x_years: nombre ou null

      Si erreur ou plus de nouveaux items, renvoyer [].
    PROMPT
  end

  def create_plan
    create_prompt()
    #prompt to chatGPT
    client = RubyLLM::Chat.new

      @response = client.ask(@prompt)
      # raise

    #Answerformat to an array of hashes
    array = JSON.parse(@response.content)
    raise
    #For each line, create a new maintenance item in the PlanItem table
    array.each do |item|
      item.symbolize_keys!
      MaintenanceItem.create(car_id: @car.id, item_name: item[:item_name], to_do_every_x_km: item[:to_do_every_x_km], to_do_every_x_years: item[:to_do_every_x_years], one_shot_operation: item[:one_shot_operation])
    end
  end

end

app/helpers/maintenance_items_helper.rb
module MaintenanceItemsHelper
end

app/views/maintenance_items/_form.html.erb
<% is_readonly = local_assigns[:readonly] || false %>

<form action="<%= form_action %>" method="<%= form_method %>">
  <% if form_method.to_s.downcase != "post" %>
    <input type="hidden" name="_method" value="<%= form_method.upcase %>">
  <% end %>

  <label for="car_id">Voiture</label>
  <input type="text" name="maintenance_item[car_id]" id="car_id" value="<%= @car.id %>" <%= 'readonly' if is_readonly %>><br>

  <label for="item_name">Opération</label>
  <input type="text" name="maintenance_item[item_name]" id="item_name" value="<%=maintenance_item&.item_name %>" <%= 'readonly' if is_readonly %>><br>

  <label for="one_shot_operation">Operation unique</label>
  <input type="checkbox" name="maintenance_item[one_shot_operation]" id="one_shot_operation" value="<%=maintenance_item&.one_shot_operation %>" <%= 'readonly' if is_readonly %>><br>

  <label for="to_do_every_x_km">A faire tous les</label>
  <input type="text" name="maintenance_item[to_do_every_x_km]" id="to_do_every_x_km" value="<%=maintenance_item&.to_do_every_x_km %>" <%= 'readonly' if is_readonly %>>
  <span> km</span><br>

  <label for="to_do_every_x_years">A faire tous les</label>
  <input type="text" name="maintenance_item[to_do_every_x_years]" id="to_do_every_x_years" value="<%=maintenance_item&.to_do_every_x_years %>" <%= 'readonly' if is_readonly %>>
  <span> an</span><br>

  <% unless is_readonly %>
    <input type="submit" value="Valider">
  <% end %>
</form>

app/views/maintenance_items/edit.html.erb
hello from edit_maintenance_item

<%= render partial: 'form', locals: {
  car: @car,
  maintenance_item: @maintenance_item,
  form_action: car_maintenance_item_path(@car, @maintenance_item),
  form_method: "patch"
} %>

app/views/maintenance_items/index.html.erb
hello from maintenance_items index

<p><%=link_to "nouveau" , new_car_maintenance_item_path%></p>

<%if @car.maintenance_items.empty?%>
  <div>
    <p>pas d'opération déclarée dans le plan d'entretien</p>
    <%= link_to "créer le plan d'entretien", car_maintenance_items_call_maintenance_path(@car) %>
  </div>

<%else%>
  <%= link_to "mettre à jour le plan d'entretien", car_maintenance_items_call_maintenance_path(@car) %>
  <ul>
    <%i = 0%>
    <%@car.maintenance_items.each do |item|%>
      <li><%=i%> - <%=link_to item.item_name , car_maintenance_item_path(@car, item)%></li>
      <% i = i+1%>
    <%end%>
  </ul>
<%end%>

app/views/maintenance_items/new.html.erb
hello from maintenance_items new

<h1>Maintenance_item#new</h1>


<%= render partial: 'form', locals: {
  car: @car,
  maintenance_item: @maintenance_item,
  form_action: car_maintenance_items_path,
  form_method: "post"
} %>

app/views/maintenance_items/show.html.erb
hello from maintenance_items show

<%= render partial: 'form', locals: {
  car: @car,
  maintenance_item: @maintenance_item,
  form_action: "#",
  form_method: "get",
  readonly: true
} %>

<a href="<%=edit_car_maintenance_item_path(@car, @maintenance_item)%>">Mise à jour</a>