config/routes.rb
Rails.application.routes.draw do
  get 'cars/index'
  get 'cars/new'
  get 'cars/create'
  get 'cars/edit'
  get 'cars/update'
  get 'cars/destroy'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cars#index"

  #definitions des routes une par une, sans refacto pour la pratique en utilisant resources
  get "cars/", to: "cars#index", as: "cars"
  get "cars/new", to: "cars#new", as: "new_car"
  get "cars/:id", to: "cars#show", as: "car"
  post "cars", to: "cars#create"
  get "cars/:id/edit", to: "cars#edit", as: "edit_car"
  patch "cars/:id", to: "cars#update"
  delete "cars/:id", to: "cars#destroy"

  get "cars/:car_id/maintenance_items/", to: "maintenance_items#index", as: "car_maintenance_items"
  get "cars/:car_id/maintenance_items/call_maintenance", to: "maintenance_items#call_maintenance", as: "car_maintenance_items_call_maintenance"
  get "cars/:car_id/maintenance_items/new", to: "maintenance_items#new", as: "new_car_maintenance_item"
  get "cars/:car_id/maintenance_items/:id", to: "maintenance_items#show", as: "car_maintenance_item"
  post "cars/:car_id/maintenance_items", to: "maintenance_items#create"
  get "cars/:car_id/maintenance_items/:id/edit", to: "maintenance_items#edit", as: "edit_car_maintenance_item"
  patch "cars/:car_id/maintenance_items/:id", to: "maintenance_items#update"
  delete "cars/:car_id/maintenance_items/:id", to: "maintenance_items#destroy"

  get "cars/:car_id/garage_stops/", to: "garage_stops#index", as: "car_garage_stops"
  get "cars/:car_id/garage_stops/new", to: "garage_stops#new", as: "new_car_garage_stop"
  get "cars/:car_id/garage_stops/picture_analysis", to: "garage_stops#picture_analysis", as: "new_car_garage_stop_picture_analysis"
  post "cars/:car_id/garage_stops/invoice_review", to: "garage_stops#invoice_review", as: "new_car_garage_stop_invoice_review"
  get "cars/:car_id/garage_stops/:id", to: "garage_stops#show", as: "car_garage_stop"
  post "cars/:car_id/garage_stops", to: "garage_stops#create"
  get "cars/:car_id/garage_stops/:id/edit", to: "garage_stops#edit", as: "edit_car_garage_stop"
  patch "cars/:car_id/garage_stops/:id", to: "garage_stops#update"
  delete "cars/:car_id/garage_stops/:id", to: "garage_stops#destroy"

  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/", to: "stop_items#index", as: "car_garage_stop_stop_items"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/new", to: "stop_items#new", as: "new_car_garage_stop_stop_item"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#show", as: "car_garage_stop_stop_item"
  post "cars/:car_id/garage_stops/:garage_stop_id/stop_items", to: "stop_items#create"
  get "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id/edit", to: "stop_items#edit", as: "edit_car_garage_stop_stop_item"
  patch "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#update"
  delete "cars/:car_id/garage_stops/:garage_stop_id/stop_items/:id", to: "stop_items#destroy"

  get "garages/", to: "garages#index", as: "garages"
  get "garages/new", to: "garages#new", as: "new_garage"
  get "garages/:id", to: "garages#show", as: "garage"
  post "garages", to: "garages#create"
  get "garages/:id/edit", to: "garages#edit", as: "edit_garage"
  patch "garages/:id", to: "garages#update"
  delete "garages/:id", to: "garages#destroy"

  get "picture_analysis", to: "image_data#picture_analysis", as: "new_picture_analysis"
  post "invoice_review", to: "image_data#invoice_review", as: "new_invoice_review"

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :maintenance_items
  has_many :garage_stops

  # validates :number_plate, presence: true, uniqueness: true
  # validates :model, presence: true
  # validates :make, presence: true
  # validates :mileage, presence: true
  # validates :first_registration_date, presence: true
  # validates :energy, presence: true
  # validates :horsepower, presence: true

  # validates , presence: true
  # validates :model, presence: true

  has_many :garage_stops
  has_many :maintenance_items

  ENERGIE = [
  { id: "essence",          label: "Essence" },
  { id: "diesel",           label: "Diesel" },
  { id: "hybrid",           label: "Hybride" },
  { id: "plug-in_hybrid",   label: "Hybride rechargeable" },
  { id: "electric",         label: "Electrique" },
  { id: "hybrid_diesel",    label: "Hybride-diesel" },
  { id: "hydrogen",         label: "Hydrogène" },
  { id: "lpg",              label: "GPL" },
  { id: "bioethanol",       label: "Bicarburation essence-éthanol"}
  ].freeze

  USES = [
  { id: "commute",          label: "Domicile-travail" },
  { id: "use_for_work",     label: "Outil de travail" },
  { id: "weekend",          label: "Week-ends" },
  { id: "winter_holidays",  label: "Vacances d'hiver" },
  { id: "spring_holidays",  label: "Vacances de printemps" },
  { id: "summer_holidays",  label: "Vacances d'été" },
  { id: "fall_holidays",    label: "Vacances d'automne" }
  ].freeze

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
before_action :set_car, only: [:show, :edit, :update]
# before_action :car_params, only: [:create]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    # puts car_params.inspect

    @car = Car.new(car_params)
    # @car.use = params[:car][:use].to_s
    # raise
    if @car.save
      # raise
      redirect_to cars_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    # raise
  end

  def update
    # raise
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:user_id, :number_plate, :make, :model, :energy, :horsepower, :first_registration_date, :mileage, :mileage_per_year, :use, :last_technical_control_date, :last_maintenance_operation_made_on, :last_maintenance_operation_mileage, :energy, use: [])
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<% is_readonly = local_assigns[:readonly] || false %>

<form action="<%= form_action %>" method="<%= form_method %>">
  <% if form_method.to_s.downcase != "post" %>
    <input type="hidden" name="_method" value="<%= form_method.upcase %>">
  <% end %>

  <label for="user_id">Utilisateur</label>
  <input type="text" name="car[user_id]" id="user_id" value="<%= car&.user_id %>" <%= 'readonly' if is_readonly %>><br>

  <label for="number_plate">N° immatriculation</label>
  <input type="text" name="car[number_plate]" id="number_plate" value="<%= car&.number_plate %>" <%= 'readonly' if is_readonly %>><br>

  <label for="make">Marque</label>
  <input type="text" name="car[make]" id="make" value="<%= car&.make %>" <%= 'readonly' if is_readonly %>><br>

  <label for="model">Modèle</label>
  <input type="text" name="car[model]" id="model" value="<%= car&.model %>" <%= 'readonly' if is_readonly %>><br>

  <div>
    <p for="energy">Energie</p>
    <% Car::ENERGIE.each do |e| %>
      <input type="radio" id=<%=e[:id]%> name="car[energy]" value=<%=e[:label]%>>
      <label for=<%=e[:id]%>><%=e[:label]%></label><br>
    <%end%>
  </div>

  <label for="horsepower">Puissance</label>
  <input type="number" name="car[horsepower]" id="horsepower" value="<%= car&.horsepower %>" <%= 'readonly' if is_readonly %>><br>

  <label for="first_registration_date">Date de mise en circulation</label>
  <input type="date" name="car[first_registration_date]" id="first_registration_date" value="<%= car&.first_registration_date %>" <%= 'readonly' if is_readonly %>><br>

  <label for="mileage">Kilomètrage</label>
  <input type="number" name="car[mileage]" id="mileage" value="<%= car&.mileage %>" <%= 'readonly' if is_readonly %>><br>

  <label for="mileage_per_year">Kilomètrage par an</label>
  <input type="number" name="car[mileage_per_year]" id="mileage_per_year" value="<%= car&.mileage_per_year %>" <%= 'readonly' if is_readonly %>><br>

  <div>
    <p for="use">Utilisation</p>
    <% Car::USES.each do |u| %>
      <%= check_box_tag "car[use][]", u[:id], @car&.use&.include?(u[:id]),
        id: u[:id],
        disabled: is_readonly,
        class: (is_readonly ? 'readonly' : '')
      %>
      <%= label_tag u[:id], u[:label] %><br>
    <% end %>
    <br><br>
  </div>

  <label for="last_technical_control_date">Date du dernier Contrôle Technique</label>
  <input type="date" name="car[last_technical_control_date]" id="last_technical_control_date" value="<%= car&.last_technical_control_date%>" <%= 'readonly' if is_readonly %>><br>

  <label for="last_maintenance_operation_made_on">Date du dernier entretien</label>
  <input type="date" name="car[last_maintenance_operation_made_on]" id="last_maintenance_operation_made_on" value="<%= car&.last_maintenance_operation_made_on %>" <%= 'readonly' if is_readonly %>><br>

  <label for="last_maintenance_operation_mileage">Kilomètrage du dernier entretien</label>
  <input type="number" name="car[last_maintenance_operation_mileage]" id="last_maintenance_operation_mileage" value="<%= car&.last_maintenance_operation_mileage %>" <%= 'readonly' if is_readonly %>><br>

  <% unless is_readonly %>
    <input type="submit" value="Valider">
  <% end %>
</form>

app/views/cars/edit.html.erb
<h1>Cars#edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

<%= render partial: 'form', locals: {
  car: @car,
  form_action: car_path(@car),
  form_method: "patch"
} %>

app/views/cars/index.html.erb
<h1>Cars#index</h1>
<p>Find me in app/views/cars/index.html.erb</p>

<p><%=link_to "nouveau" ,new_car_path%></p>

<ul>
 <%@cars.each do |car|%>
  <li><%=link_to car.make ,car_path(car)%></li>
  <%end%>
</ul>

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>


<%= render partial: 'form', locals: {
  car: @car,
  form_action: cars_path,
  form_method: "post"
} %>

app/views/cars/show.html.erb
<p>fiche de <%=@car.make%> <%=@car.model%> - <%=@car.number_plate%></p>

<%= render partial: 'form', locals: {
  car: @car,
  form_action: "#",
  form_method: "get",
  readonly: true
} %>

<a href="<%=edit_car_path(@car)%>">Mise à jour</a>

<a href="<%=car_maintenance_items_path(@car)%>">Plan d'entretien</a>
<a href="<%=car_garage_stops_path(@car)%>">Passages au garage</a>